CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
APELLIDO1 VARCHAR(30) NOT NULL,
APELLIDO2 VARCHAR(30) NOT NULL,
FECHA_NACIMIENTO DATE
);

CREATE TABLE TELEFONOS_CLIENTE(
TELEFONO INT NOT NULL PRIMARY KEY,
CLIENTE INT NOT NULL,
FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CORREOS_CLIENTE(
ID_CORREO INT NOT NULL PRIMARY KEY,
CLIENTE INT NOT NULL,
CORREO VARCHAR(50) NOT NULL,
FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ORIGEN(
ID_ORIGEN INT NOT NULL PRIMARY KEY,
NOMBRE_CIUDAD VARCHAR(50),
DESCRIPCION VARCHAR(80)
);

CREATE TABLE DESTINO(
ID_DESTINO INT NOT NULL PRIMARY KEY,
NOMBRE_CIUDAD VARCHAR(50),
DESCRIPCION VARCHAR(80)

);

CREATE TABLE TRANSPORTE(
ID_TRANSPORTE INT NOT NULL PRIMARY KEY,
FECHA_HORA_PARTIDA DATE,
FECHA_HORA_LLEGADA DATE,
ORIGEN INT NOT NULL ,
DESTINO INT NOT NULL,
EMPRESA_TRANSPORTE INT NOT NULL,
PRECIO_TRANSPORTE DECIMAL(8,2)
);

CREATE TABLE EMPRESA_TRANSPORTE(
ID_EMPRESA INT NOT NULL PRIMARY KEY,
NOMBRE_EMPRESA VARCHAR(45) NOT NULL,
TELEFONO INT NOT NULL
);

CREATE TABLE TOUR(
ID_TOUR INT NOT NULL PRIMARY KEY,
NOMBRE_TOUR VARCHAR(45) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
PRECIO_TOUR DECIMAL(8,2)
);

CREATE TABLE ITINERARIO(
ID_ITINERARIO INT NOT NULL PRIMARY KEY,
DESTINO INT NOT NULL,
ORIGEN INT NOT NULL,
TIPO_TOUR INT NOT NULL,
CANTIDAD_HORAS INT NOT NULL,
FOREIGN KEY(DESTINO) REFERENCES DESTINO(ID_DESTINO),
FOREIGN KEY(ORIGEN) REFERENCES ORIGEN(ID_ORIGEN),
FOREIGN KEY(TIPO_TOUR) REFERENCES TOUR (ID_TOUR)
);

CREATE TABLE FACTURAS(
ID_FACTURA INT NOT NULL PRIMARY KEY,
COD_CLIENTE INT NOT NULL,
COD_TRANSPORTE INT NOT NULL,
COD_ITINERARIO INT NOT NULL,
FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(COD_TRANSPORTE) REFERENCES TRANSPORTE(ID_TRANSPORTE),
FOREIGN KEY(COD_ITINERARIO) REFERENCES ITINERARIO(ID_ITINERARIO)
);

CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE(
    ID_C IN INT,
  NOMBRE IN VARCHAR,
  APE1 IN VARCHAR,
  APE2 IN VARCHAR,
  FECHA_NAC IN DATE
)
IS
BEGIN
  INSERT INTO CLIENTE(ID_CLIENTE, NOMBRE_CLIENTE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO)
  VALUES (ID_C, NOMBRE, APE1, APE2, FECHA_NAC);
END INSERTAR_CLIENTE;


CREATE OR REPLACE PROCEDURE LEER_CLIENTE(
  ID_C IN INT,
  NOMBRE OUT VARCHAR,
  APE1 OUT VARCHAR,
  APE2 OUT VARCHAR,
  FECHA_NAC OUT DATE
)
IS
BEGIN
  SELECT NOMBRE_CLIENTE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO
  INTO NOMBRE, APE1, APE2, FECHA_NAC
  FROM CLIENTE
  WHERE ID_CLIENTE = ID_C;
END LEER_CLIENTE;


CREATE OR REPLACE PROCEDURE ACTUALIZAR_CLIENTE(
  ID_CLIENTE IN INT,
  NOMBRE_CLIENTE IN VARCHAR,
  APELLIDO1 IN VARCHAR,
  APELLIDO2 IN VARCHAR,
  FECHA_NACIMIENTO IN DATE
)
IS
BEGIN
  UPDATE CLIENTE
  SET NOMBRE_CLIENTE = NOMBRE_CLIENTE,
      APELLIDO1 = APELLIDO1,
      APELLIDO2 = APELLIDO2,
      FECHA_NACIMIENTO = FECHA_NACIMIENTO
  WHERE ID_CLIENTE = ID_CLIENTE;
END ACTUALIZAR_CLIENTE;

CREATE OR REPLACE PROCEDURE ELIMINAR_CLIENTE(
  ID_CLIENTE IN INT
)
IS
BEGIN
  DELETE FROM CLIENTE
  WHERE ID_CLIENTE = ID_CLIENTE;
END ELIMINAR_CLIENTE;


CREATE PROCEDURE INSERTAR_TELEFONO_CLIENTE(
  TELEFONO IN INT,
  CLIENTE IN INT
)
IS
BEGIN
  INSERT INTO TELEFONOS_CLIENTE(TELEFONO, CLIENTE)
  VALUES (TELEFONO, CLIENTE);
END INSERTAR_TELEFONO_CLIENTE;

CREATE PROCEDURE LEER_TELEFONO_CLIENTE(
  TELEFONO IN INT,
  CLIENTE IN INT,
  TELEFONO_OUT OUT INT
)
IS
BEGIN
  SELECT TELEFONO
  INTO TELEFONO_OUT
  FROM TELEFONOS_CLIENTE
  WHERE TELEFONO = TELEFONO AND CLIENTE = CLIENTE;
END LEER_TELEFONO_CLIENTE;

CREATE PROCEDURE ACTUALIZAR_TELEFONO_CLIENTE(
  TELEFONO_IN IN INT,
  CLIENTE_IN IN INT,
  TELEFONO_OUT IN INT
)
IS
BEGIN
  UPDATE TELEFONOS_CLIENTE
  SET TELEFONO = TELEFONO_OUT
  WHERE TELEFONO = TELEFONO_IN AND CLIENTE = CLIENTE_IN;
END ACTUALIZAR_TELEFONO_CLIENTE;

CREATE PROCEDURE ELIMINAR_TELEFONO_CLIENTE(
  TELEFONO IN INT,
  CLIENTE IN INT
)
IS
BEGIN
  DELETE FROM TELEFONOS_CLIENTE
  WHERE TELEFONO = TELEFONO AND CLIENTE = CLIENTE;
END ELIMINAR_TELEFONO_CLIENTE;

CREATE OR REPLACE PROCEDURE INSERTAR_CORREO_CLIENTE(
  P_ID_CORREO INT,
  P_CLIENTE INT,
  P_CORREO VARCHAR
) AS
BEGIN
  INSERT INTO CORREOS_CLIENTE(ID_CORREO, CLIENTE, CORREO)
  VALUES (P_ID_CORREO, P_CLIENTE, P_CORREO);
  COMMIT;
END INSERTAR_CORREO_CLIENTE;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_CORREO_CLIENTE(
  P_ID_CORREO INT,
  P_CORREO VARCHAR
) AS
BEGIN
  UPDATE CORREOS_CLIENTE SET CORREO = P_CORREO
  WHERE ID_CORREO = P_ID_CORREO;
  COMMIT;
END ACTUALIZAR_CORREO_CLIENTE;

CREATE OR REPLACE PROCEDURE ELIMINAR_CORREO_CLIENTE(
  P_ID_CORREO INT
) AS
BEGIN
  DELETE FROM CORREOS_CLIENTE
  WHERE ID_CORREO = P_ID_CORREO;
  COMMIT;
END ELIMINAR_CORREO_CLIENTE;

CREATE OR REPLACE PROCEDURE LEER_CORREO_CLIENTE(
  P_ID_CORREO INT,
  P_CLIENTE OUT INT,
  P_CORREO OUT VARCHAR
) AS
BEGIN
  SELECT CLIENTE, CORREO INTO P_CLIENTE, P_CORREO
  FROM CORREOS_CLIENTE
  WHERE ID_CORREO = P_ID_CORREO;
END LEER_CORREO_CLIENTE;

CREATE PROCEDURE INSERTAR_ORIGEN(
  ID_ORIGEN IN INT,
  NOMBRE_CIUDAD IN VARCHAR,
  DESCRIPCION IN VARCHAR
)
IS
BEGIN
  INSERT INTO ORIGEN(ID_ORIGEN, NOMBRE_CIUDAD, DESCRIPCION)
  VALUES (ID_ORIGEN, NOMBRE_CIUDAD, DESCRIPCION);
END INSERTAR_ORIGEN;

CREATE PROCEDURE LEER_ORIGEN(
  ID_ORIGEN IN INT,
  OUT NOMBRE_CIUDAD VARCHAR,
  OUT DESCRIPCION VARCHAR
)
IS
BEGIN
  SELECT NOMBRE_CIUDAD, DESCRIPCION
  INTO NOMBRE_CIUDAD, DESCRIPCION
  FROM ORIGEN
  WHERE ID_ORIGEN = ID_ORIGEN;
END LEER_ORIGEN;

CREATE PROCEDURE ACTUALIZAR_ORIGEN(
  ID_ORIGEN IN INT,
  NOMBRE_CIUDAD IN VARCHAR,
  DESCRIPCION IN VARCHAR
)
IS
BEGIN
  UPDATE ORIGEN
  SET NOMBRE_CIUDAD = NOMBRE_CIUDAD, DESCRIPCION = DESCRIPCION
  WHERE ID_ORIGEN = ID_ORIGEN;
END ACTUALIZAR_ORIGEN;

CREATE PROCEDURE ELIMINAR_ORIGEN(
  ID_ORIGEN IN INT
)
IS
BEGIN
  DELETE FROM ORIGEN
  WHERE ID_ORIGEN = ID_ORIGEN;
END ELIMINAR_ORIGEN;


CREATE PROCEDURE INSERTAR_DESTINO(
  ID_DESTINO IN INT,
  NOMBRE_CIUDAD IN VARCHAR,
  DESCRIPCION IN VARCHAR
)
IS
BEGIN
  INSERT INTO DESTINO(ID_DESTINO, NOMBRE_CIUDAD, DESCRIPCION)
  VALUES (ID_DESTINO,, NOMBRE_CIUDAD, DESCRIPCION);
END INSERTAR_DESTINO;

CREATE PROCEDURE LEER_DESTINO(
  ID_DESTINO IN INT,
  NOMBRE_CIUDAD OUT VARCHAR,
  DESCRIPCION OUT VARCHAR
)
IS
BEGIN
  SELECT NOMBRE_CIUDAD, DESCRIPCION
  INTO NOMBRE_CIUDAD, DESCRIPCION
  FROM DESTINO
  WHERE ID_DESTINO = ID_DESTINO;
END LEER_DESTINO;

CREATE PROCEDURE ACTUALIZAR_DESTINO(
  ID_DESTINO IN INT,
  NOMBRE_CIUDAD IN VARCHAR,
  DESCRIPCION IN VARCHAR
)
IS
BEGIN
  UPDATE DESTINO
  SET NOMBRE_CIUDAD = NOMBRE_CIUDAD, DESCRIPCION = DESCRIPCION
  WHERE ID_DESTINO = ID_DESTINO;
END ACTUALIZAR_DESTINO;

CREATE PROCEDURE ELIMINAR_DESTINO(
  ID_DESTINO IN INT
)
IS
BEGIN
  DELETE FROM DESTINO
  WHERE ID_DESTINO = ID_DESTINO;
END ELIMINAR_DESTINO;

CREATE OR REPLACE PROCEDURE INSERTAR_TRANSPORTE(
  ID_TRANSPORTE IN INT,
  FECHA_HORA_PARTIDA IN DATE,
  FECHA_HORA_LLEGADA IN DATE,
  ORIGEN IN INT,
  DESTINO IN INT,
  EMPRESA_TRANSPORTE IN INT,
  PRECIO_TRANSPORTE IN DECIMAL
)
IS
BEGIN
  INSERT INTO TRANSPORTE(ID_TRANSPORTE, FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, ORIGEN, DESTINO, EMPRESA_TRANSPORTE, PRECIO_TRANSPORTE)
  VALUES (ID_TRANSPORTE, FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, ORIGEN, DESTINO, EMPRESA_TRANSPORTE, PRECIO_TRANSPORTE);
END INSERTAR_TRANSPORTE;

CREATE OR REPLACE PROCEDURE LEER_TRANSPORTE(
  ID_TRANSPORTE IN INT,
  FECHA_HORA_PARTIDA OUT DATE,
  FECHA_HORA_LLEGADA OUT DATE,
  ORIGEN OUT INT,
  DESTINO OUT INT,
  EMPRESA_TRANSPORTE OUT INT,
  PRECIO_TRANSPORTE OUT DECIMAL
)
IS
BEGIN
  SELECT FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, ORIGEN, DESTINO, EMPRESA_TRANSPORTE, PRECIO_TRANSPORTE
  INTO FECHA_HORA_PARTIDA, FECHA_HORA_LLEGADA, ORIGEN, DESTINO, EMPRESA_TRANSPORTE, PRECIO_TRANSPORTE
  FROM TRANSPORTE
  WHERE ID_TRANSPORTE = ID_TRANSPORTE;
END LEER_TRANSPORTE;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_TRANSPORTE(
  ID_TRANSPORTE IN INT,
  FECHA_HORA_PARTIDA IN DATE,
  FECHA_HORA_LLEGADA IN DATE,
  ORIGEN IN INT,
  DESTINO IN INT,
  EMPRESA_TRANSPORTE IN INT,
  PRECIO_TRANSPORTE IN DECIMAL
)
IS
BEGIN
  UPDATE TRANSPORTE
  SET FECHA_HORA_PARTIDA = FECHA_HORA_PARTIDA,
      FECHA_HORA_LLEGADA = FECHA_HORA_LLEGADA,
      ORIGEN = ORIGEN,
      DESTINO = DESTINO,
      EMPRESA_TRANSPORTE = EMPRESA_TRANSPORTE,
      PRECIO_TRANSPORTE = PRECIO_TRANSPORTE
  WHERE ID_TRANSPORTE = ID_TRANSPORTE;
END ACTUALIZAR_TRANSPORTE;

CREATE OR REPLACE PROCEDURE ELIMINAR_TRANSPORTE(
  ID_TRANSPORTE IN INT
)
IS
BEGIN
  DELETE FROM TRANSPORTE
  WHERE ID_TRANSPORTE = ID_TRANSPORTE;
END ELIMINAR_TRANSPORTE;

CREATE PROCEDURE INSERTAR_EMPRESA_TRANSPORTE(
   ID_EMPRESA IN INT,
    NOMBRE_EMPRESA IN VARCHAR,
    TELEFONO IN INT
)
IS
BEGIN
    INSERT INTO EMPRESA_TRANSPORTE(ID_EMPRESA, NOMBRE_EMPRESA, TELEFONO)
    VALUES(ID_EMPRESA, NOMBRE_EMPRESA, TELEFONO);
END INSERTAR_EMPRESA_TRANSPORTE;

CREATE PROCEDURE LEER_EMPRESA_TRANSPORTE(
    ID_EMPRESA IN INT,
    OUT NOMBRE_EMPRESA OUT VARCHAR,
    OUT TELEFONO OUT INT
)
IS
BEGIN
    SELECT NOMBRE_EMPRESA, TELEFONO INTO NOMBRE_EMPRESA, TELEFONO
    FROM EMPRESA_TRANSPORTE
    WHERE ID_EMPRESA = ID_EMPRESA;
END LEER_EMPRESA_TRANSPORTE;


CREATE PROCEDURE ACTUALIZAR_EMPRESA_TRANSPORTE(
    ID_EMPRESA IN INT,
    NOMBRE_EMPRESA IN VARCHAR,
    TELEFONO IN INT
)
IS
BEGIN
    UPDATE EMPRESA_TRANSPORTE
    SET NOMBRE_EMPRESA = NOMBRE_EMPRESA, TELEFONO = TELEFONO
    WHERE ID_EMPRESA = ID_EMPRESA;
END ACTUALIZAR_EMPRESA_TRANSPORTE;

CREATE PROCEDURE ELIMINAR_EMPRESA_TRANSPORTE(
    ID_EMPRESA IN INT
)
IS
BEGIN
    DELETE FROM EMPRESA_TRANSPORTE
    WHERE ID_EMPRESA = ID_EMPRESA;
END ELIMINAR_EMPRESA_TRANSPORTE;

CREATE PROCEDURE INSERTAR_TOUR(
ID_TOUR IN INT,
  NOMBRE_TOUR IN VARCHAR,
  DESCRIPCION IN VARCHAR,
  PRECIO_TOUR IN DECIMAL
)
IS
BEGIN
  INSERT INTO TOUR(ID_TOUR, NOMBRE_TOUR, DESCRIPCION, PRECIO_TOUR)
  VALUES (ID_TOUR, NOMBRE_TOUR, DESCRIPCION, PRECIO_TOUR);
END INSERTAR_TOUR;

CREATE PROCEDURE LEER_TOUR(
  ID_TOUR IN INT,
  NOMBRE_TOUR OUT VARCHAR,
  DESCRIPCION OUT VARCHAR,
  PRECIO_TOUR OUT DECIMAL
)
IS
BEGIN
  SELECT NOMBRE_TOUR, DESCRIPCION, PRECIO_TOUR
  INTO NOMBRE_TOUR, DESCRIPCION, PRECIO_TOUR
  FROM TOUR
  WHERE ID_TOUR = ID_TOUR;
END LEER_TOUR;

CREATE PROCEDURE ACTUALIZAR_TOUR(
  ID_TOUR IN INT,
  NOMBRE_TOUR IN VARCHAR,
  DESCRIPCION IN VARCHAR,
  PRECIO_TOUR IN DECIMAL
)
IS
BEGIN
  UPDATE TOUR
  SET NOMBRE_TOUR = NOMBRE_TOUR, DESCRIPCION = DESCRIPCION, PRECIO_TOUR = PRECIO_TOUR
  WHERE ID_TOUR = ID_TOUR;
END ACTUALIZAR_TOUR;

CREATE PROCEDURE ELIMINAR_TOUR(
  ID_TOUR IN INT
)
IS
BEGIN
  DELETE FROM TOUR
  WHERE ID_TOUR = ID_TOUR;
END ELIMINAR_TOUR;


CREATE PROCEDURE INSERTAR_ITINERARIO(
ID_ITINERARIO IN INT,
  DESTINO IN INT,
  ORIGEN IN INT,
  TIPO_TOUR IN INT,
  CANTIDAD_HORAS IN INT
)
IS
BEGIN
  INSERT INTO ITINERARIO(ID_ITINERARIO, DESTINO, ORIGEN, TIPO_TOUR, CANTIDAD_HORAS)
  VALUES (ID_ITINERARIO, DESTINO, ORIGEN, TIPO_TOUR, CANTIDAD_HORAS);
END INSERTAR_ITINERARIO;

CREATE PROCEDURE LEER_ITINERARIO(
  ID_ITINERARIO IN INT,
  DESTINO OUT INT,
  ORIGEN OUT INT,
  TIPO_TOUR OUT INT,
  CANTIDAD_HORAS OUT INT
)
IS
BEGIN
  SELECT DESTINO, ORIGEN, TIPO_TOUR, CANTIDAD_HORAS
  INTO DESTINO, ORIGEN, TIPO_TOUR, CANTIDAD_HORAS
  FROM ITINERARIO
  WHERE ID_ITINERARIO = ID_ITINERARIO;
END LEER_ITINERARIO;

CREATE PROCEDURE ACTUALIZAR_ITINERARIO(
  ID_ITINERARIO IN INT,
  DESTINO IN INT,
  ORIGEN IN INT,
  TIPO_TOUR IN INT,
  CANTIDAD_HORAS IN INT
)
IS
BEGIN
  UPDATE ITINERARIO
  SET DESTINO = DESTINO,
      ORIGEN = ORIGEN,
      TIPO_TOUR = TIPO_TOUR,
      CANTIDAD_HORAS = CANTIDAD_HORAS
  WHERE ID_ITINERARIO = ID_ITINERARIO;
END ACTUALIZAR_ITINERARIO;

CREATE PROCEDURE ELIMINAR_ITINERARIO(
  ID_ITINERARIO IN INT
)
IS
BEGIN
  DELETE FROM ITINERARIO
  WHERE ID_ITINERARIO = ID_ITINERARIO;
END ELIMINAR_ITINERARIO;

-- Procedimiento almacenado para crear una nueva factura
CREATE PROCEDURE INSERTAR_FACTURA(
  COD_FACTURA IN INT,
  COD_CLIENTE IN INT,
  COD_TRANSPORTE IN INT,
  COD_ITINERARIO IN INT
)
IS
BEGIN
  INSERT INTO FACTURAS(ID_FACTURA, COD_CLIENTE, COD_TRANSPORTE, COD_ITINERARIO)
  VALUES (COD_FACTURA, COD_CLIENTE, COD_TRANSPORTE, COD_ITINERARIO);
END INSERTAR_FACTURA;

CREATE PROCEDURE LEER_FACTURA(
  COD_FACTURA IN INT,
  OUT_COD_CLIENTE OUT INT,
  OUT_COD_TRANSPORTE OUT INT,
  OUT_COD_ITINERARIO OUT INT
)
IS
BEGIN
  SELECT COD_CLIENTE, COD_TRANSPORTE, COD_ITINERARIO
  INTO OUT_COD_CLIENTE, OUT_COD_TRANSPORTE, OUT_COD_ITINERARIO
  FROM FACTURAS
  WHERE ID_FACTURA = COD_FACTURA;
END LEER_FACTURA;

CREATE PROCEDURE ACTUALIZAR_FACTURA(
  COD_FACTURA IN INT,
  COD_CLIENTE IN INT,
  COD_TRANSPORTE IN INT,
  COD_ITINERARIO IN INT
)
IS
BEGIN
  UPDATE FACTURAS
  SET COD_CLIENTE = COD_CLIENTE, COD_TRANSPORTE = COD_TRANSPORTE, COD_ITINERARIO = COD_ITINERARIO
  WHERE ID_FACTURA = COD_FACTURA;
END ACTUALIZAR_FACTURA;

CREATE PROCEDURE ELIMINAR_FACTURA(
  COD_FACTURA IN INT
)
IS
BEGIN
  DELETE FROM FACTURAS
  WHERE ID_FACTURA = COD_FACTURA;
END ELIMINAR_FACTURA;

